# Generated by Django 5.0.6 on 2024-07-01 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casocliente',
            old_name='fecha',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='casocliente',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='casocliente',
            name='estado',
            field=models.CharField(default='En espera', max_length=20),
        ),
        migrations.AlterField(
            model_name='casocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.clientepotencial'),
        ),
    ]
