# Generated by Django 5.0.6 on 2024-07-01 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_casocliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='casocliente',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='casocliente',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=255),
        ),
        migrations.AlterField(
            model_name='casocliente',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto')], default='Pendiente', max_length=20),
        ),
    ]
