# Generated by Django 5.0.6 on 2024-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_casocliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casocliente',
            name='email_cliente',
        ),
        migrations.RemoveField(
            model_name='casocliente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='casocliente',
            name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='casocliente',
            name='telefono_cliente',
        ),
        migrations.AlterField(
            model_name='casocliente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20),
        ),
    ]
