# Generated by Django 5.0.6 on 2024-07-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_casocliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casocliente',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto')], default='pendiente', max_length=20),
        ),
    ]
