# Generated by Django 5.0.6 on 2024-07-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_casocliente_fecha_casocliente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casocliente',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
    ]
